### ISSUE TITLE
gptassistant.json

### ISSUE THREAD

**Issue by glinko** [RIvance/minecraft-chatgpt-assistant#8]
I got an error when I try to add API key manually in gptassistant.json
I use dockerized fabric server from https://github.com/itzg/docker-minecraft-server

{
  "token": "sk----------my----------token",
  "proxy": "",
  "timeoutSecond": 0,
  "model": "GPT_35_TURBO_0301",
  "maxTokens": 128,
  "temperature": 0.9,
  "topP": 1.0,
  "frequencyPenalty": 0.0,
  "presencePenalty": 0.0
}

errors log:

[17:19:16] [main/INFO]: Initializing OpenAI service
[17:19:16] [main/INFO]: Starting McGPT!
[17:19:16] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gptassistant'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.4-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:70) ~[com_squareup_okhttp3_okhttp-4.10.0-f5a5c395b9f992d1.jar:?]
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309) ~[com_squareup_okhttp3_okhttp-4.10.0-f5a5c395b9f992d1.jar:?]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41) ~[com_squareup_okhttp3_okhttp-4.10.0-f5a5c395b9f992d1.jar:?]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47) ~[com_squareup_okhttp3_okhttp-4.10.0-f5a5c395b9f992d1.jar:?]
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471) ~[com_squareup_okhttp3_okhttp-4.10.0-f5a5c395b9f992d1.jar:?]
	at com.theokanning.openai.service.OpenAiService.defaultClient(OpenAiService.java:336) ~[com_theokanning_openai-gpt3-javavice-0.12.0-c7619d58f28cc2a5.jar:?]
	at com.theokanning.openai.service.OpenAiService.<init>(OpenAiService.java:76) ~[com_theokanning_openai-gpt3-javavice-0.12.0-c7619d58f28cc2a5.jar:?]
	at org.ivance.gptassistant.core.AssistantService$service$2.invoke(AssistantService.kt:33) ~[gptassistant-1.0.3-mc1194.jar:?]
	at org.ivance.gptassistant.core.AssistantService$service$2.invoke(AssistantService.kt:25) ~[gptassistant-1.0.3-mc1194.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[org_jetbrains_kotlin_kotlin-stdlib-1.8.20-9634c0b1bd16d1e7.jar:?]
	at org.ivance.gptassistant.core.AssistantService.getService(AssistantService.kt:25) ~[gptassistant-1.0.3-mc1194.jar:?]
	at org.ivance.gptassistant.core.AssistantService.<init>(AssistantService.kt:36) ~[gptassistant-1.0.3-mc1194.jar:?]
	at org.ivance.gptassistant.core.AssistantManager.createServiceFromConfig(AssistantManager.kt:31) ~[gptassistant-1.0.3-mc1194.jar:?]
	at org.ivance.gptassistant.core.AssistantManager.setConfig(AssistantManager.kt:22) ~[gptassistant-1.0.3-mc1194.jar:?]
	at org.ivance.gptassistant.ChatGptAssistantMod.setConfig(ChatGptAssistantMod.java:20) ~[gptassistant-1.0.3-mc1194.jar:?]
	at org.ivance.gptassistant.config.ModConfig.init(ModConfig.java:32) ~[gptassistant-1.0.3-mc1194.jar:?]
	at org.ivance.gptassistant.ChatGptAssistantMod.onInitialize(ChatGptAssistantMod.java:43) ~[gptassistant-1.0.3-mc1194.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 8 more

**Comment by RIvance** [comment]
Thanks for the feedback. But I'm sorry to tell you that this mod is currently a client-only mod. Server-side will be supported in the next release.
